services:
  configuration-service:
    image: configuration-service:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5440:5440"
    restart: unless-stopped
    env_file: .env
    environment:
      NODE_ENV: production
    deploy:
      restart_policy:
        condition: on-failure
